ALTER TABLE opportunities
  ADD COLUMN IF NOT EXISTS department VARCHAR(255),
  ADD COLUMN IF NOT EXISTS sub_tier VARCHAR(255),
  ADD COLUMN IF NOT EXISTS office VARCHAR(255),
  ADD COLUMN IF NOT EXISTS solicitation_number VARCHAR(128),
  ADD COLUMN IF NOT EXISTS notice_type VARCHAR(128),
  ADD COLUMN IF NOT EXISTS response_deadline TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS description_url TEXT,
  ADD COLUMN IF NOT EXISTS pop_city VARCHAR(255),
  ADD COLUMN IF NOT EXISTS pop_state VARCHAR(32),
  ADD COLUMN IF NOT EXISTS pop_zip VARCHAR(32),
  ADD COLUMN IF NOT EXISTS set_aside_code VARCHAR(128),
  ADD COLUMN IF NOT EXISTS classification_code VARCHAR(128),
  ADD COLUMN IF NOT EXISTS ui_link TEXT;
